### ISSUE TITLE
Try to do a merge from a query

### ISSUE THREAD

**Issue by hschellman** [DUNE/merge-utils#12]
merge -vvvv -q "files from fardet-hd:fardet-hd__root-tuple__v09_91_02d01__cafmaker_dune10kt_1x2x6_runreco-nuenergy_geov5__prodgenie_anu_dune10kt_1x2x6__physics__v1_official"

gives me: 

merge -vv -q "files from fardet-hd:fardet-hd__root-tuple__v09_91_02d01__cafmaker_dune10kt_1x2x6_runreco-nuenergy_geov5__prodgenie_anu_dune10kt_1x2x6__physics__v1_official"
main arguments are:  Namespace(config=None, verbose=2, local=False, query='files from fardet-hd:fardet-hd__root-tuple__v09_91_02d01__cafmaker_dune10kt_1x2x6_runreco-nuenergy_geov5__prodgenie_anu_dune10kt_1x2x6__physics__v1_official', filelist=None, files=[], list=None)
INFO: Found 0 RSEs accessible from 2 sites
INFO: Querying MetaCat for batch 0
INFO: Added 2 unique files
WARNING: RSE DUNE_US_FNAL_DISK_STAGE is too far from merging sites (inf > 1000)
WARNING: RSE FNAL_DCACHE is too far from merging sites (inf > 1000)
ERROR: Could not retrieve file fardet-hd:fardet-hd_mc_list-allanu_physics_cafmaker_dune10kt_1x2x6_runreco-nuenergy_geov5_root-tuple_merged_skip000000_lim000100_final_20241028T014118.root from Rucio
CRITICAL: File not found

despite the file being on persistent.  

In principle I should be able to run this interactively with the --local modifier but --local also seems to require -f.   Can we have --local take both -q and -f?

**Comment by hschellman** [comment]
Maybe rucio is busted? 
But I think the --local problem could be solved by substituting args.filelist for args.local in __main__.py line 43

**Comment by EthanMuldoon** [comment]
The problem is with JustIN, it asks for the distances between computing sites and RSEs but doesn't get a reply so it thinks all the RSEs are inaccessible.In the version on GitHub the --local flag is for running on local input files and there's no way to get files from MetaCat and Rucio but run the merge locally.  The next update should fix that so it works like you expect, but I made it work by just defining a local site on the config so it will still crash if it can't get the distance data from JustIN.  I played around before with pinging RSEs to see if they're accessible, maybe I'll bring that back for the local merging or something...On Jul 4, 2025 3:34 PM, Heidi Schellman ***@***.***> wrote:hschellman left a comment (DUNE/merge-utils#12)
Maybe rucio is busted?
But I think the --local problem could be solved by substituting args.filelist for args.local in main.py line 43

**Comment by hschellman** [comment]
Even if I wanted to submit to Justin, it still doesn’t seem to work.

So do you think it’s Justin being down?  Maybe get some kind of an error message for that?



Heidi Schellman
Oregon State Physics
Chair, APS Division of Particles and Fields Executive Committee



On Jul 4, 2025, at 4:02 PM, Ethan Muldoon ***@***.***> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]

[https://avatars.githubusercontent.com/u/4165521?s=20&v=4]EthanMuldoon left a comment (DUNE/merge-utils#12)<https://github.com/DUNE/merge-utils/issues/12#issuecomment-3037371429>
The problem is with JustIN, it asks for the distances between computing sites and RSEs but doesn't get a reply so it thinks all the RSEs are inaccessible.In the version on GitHub the --local flag is for running on local input files and there's no way to get files from MetaCat and Rucio but run the merge locally.  The next update should fix that so it works like you expect, but I made it work by just defining a local site on the config so it will still crash if it can't get the distance data from JustIN.  I played around before with pinging RSEs to see if they're accessible, maybe I'll bring that back for the local merging or something...On Jul 4, 2025 3:34 PM, Heidi Schellman ***@***.***> wrote:hschellman left a comment (DUNE/merge-utils#12)
Maybe rucio is busted?
But I think the --local problem could be solved by substituting args.filelist for args.local in main.py line 43

**Comment by EthanMuldoon** [comment]
Yeah, even if you're not actually using JustIN I still need the distances between sites and RSEs to figure out which Rucio replicas to use, and that comes from the JustIN database.  I just grab the csv file from the JustIN website, I can probably cache it and use the old version if the connection fails.  But then we might run into trouble if the cached version becomes outdated...

I'll also put in a check and have it print a useful error message.  The important part of the log was this rather cryptic info message about having no accessible RSEs:
INFO: Found 0 RSEs accessible from 2 sites

**Comment by hschellman** [comment]
Justin is down.  I suggest the following workaround:

Line 168 of merge_rse.py 

        # hard wire obvious options for when justin is down
        self["DUNE_US_FNAL_DISK_STAGE"].distances["US_FNAL-FermiGrid"]=0

**Comment by hschellman** [comment]
Also, it would be good to allow local running from queries - I've tried messing with the logic in __main__  I think you need the localretreiver when both file list and local are set but local and query should use the normal retriever.

**Comment by EthanMuldoon** [comment]
I think I dealt with this one a while ago by falling back to using rucio to find co-located sites and RSEs when justIN is down.
